# Generated by Django 2.2.6 on 2019-12-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date released'),
        ),
    ]
